### ISSUE TITLE
The method popular does not exist on InteractionRelation as documented

### ISSUE THREAD

**Issue by jwittekind** [multicaret/laravel-acquaintances#23] opened 2020-12-28 20:48 UTC
Do i miss something here?
To me it seems, like a wrong documentation.

**Comment by mkwsra** [comment] 2020-12-29 14:21
Perhaps you are checking a different old version

Because as you can see it's there:
[https://github.com/multicaret/laravel-acquaintances/blob/eef71ca743c6a69577bf95cbe0034e47f19f4943/src/Models/InteractionRelation.php#L53](https://github.com/multicaret/laravel-acquaintances/blob/eef71ca743c6a69577bf95cbe0034e47f19f4943/src/Models/InteractionRelation.php#L53)

**Comment by mkwsra** [comment] 2020-12-29 14:29
I will give it a try later, code-wise, in order to reproduce this issue.

**Comment by jwjuele** [comment] 2020-12-31 08:25
Where is the static method that is documented for a Trait 
`
// Model array
$posts = App\Post::popular()->get();
`

**Comment by mkwsra** [comment] 2021-01-01 10:13
Please provide the used traits within your `Post` model

**Comment by gowl** [comment] 2021-01-11 09:07
@jwjuele It seems to me that your question has been answered but please do feel free to elaborate on your issue if it wasn't. Otherwise, you can go ahead and close it, 

Just to be sure we're on the same page here, the method you sent is not a static method. It is a local scope, the same one that @mkwsra has mentioned, which goes by `scopePopular` within the model. What I understood is that you are looking for a function named `popular(...)` but do correct me if I'm wrong.

**Comment by jwjuele** [comment] 2021-01-11 10:55
I'm using an Article model with the trait "canBeFavorited", but I also tried "canBeLiked".

My goal is to query the most popular Articles. As there is a static method called "Post::popular()" documented in the ReadMe, I assumed, that i could use it on may Article Model.

When I came across an error, I took a look into the source code and could not find any definition of this documented method. 

1. So, if this method does not exist within these both traits, which traits do include it?

2. if this the method which should be used Is called "scopePopular", how do I use it, and why isn't it part of the docs?

**Closed** 2023-12-27 06:01 UTC
Labels: invalid
